import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router)
export default new Router({
  mode: 'history',
	//base: process.env.BASE_URL,
	base:'zhuzhu',
  routes: [
		//MOVIE
    {
      path:'/movie',
      name:'Movie',
			component:()=>import('@/views/Movie'),
			children:[
				{
					path:'comingsoon',
					component:()=>import('@/components/ComingSoon')
				},
				{
					path:'nowplaying',
					component:()=>import('@/components/NowPlaying')
				},
				{
					path:'search',
					component:()=>import('@/components/Search'),
				},
				{
					path:'city',
					component:()=>import('@/components/City')
				},
				{
					path:'detail/1/:movieId',
					components:{
						default:()=>import('@/components/NowPlaying'),
						detail:()=>import('@/components/Detail')
					},
					props:{detail:true}
				},
				{
					path:'detail/2/:movieId',
					components:{
						default:()=>import('@/components/ComingSoon'),
						detail:()=>import('@/components/Detail')
					},
					props:{detail:true}
				},
				{
					path:'/movie',
					redirect:'/movie/nowplaying'
				}
			]
		},
		//mine
    {
      path:'/mine',
      name:'Mine',
			component:()=>import('@/views/Mine'),
			children:[
				{
					path:'login',
					name:'Login',
					component:()=>import('@/components/Login')
				},
				{
					path:'register',
					name:'Register',
					component:()=>import('@/components/Register')
				},
				{
					path:'findpwd',
					name:'findPwd',
					component:()=>import('@/components/findPwd')
				},
				{
					path:'center',
					name:'Center',
					component:()=>import('@/components/Center')
				},
				{
					path:'/mine',
					redirect:'/mine/login'
				}
			]
		},
		//cinema
    {
      path:'/cinema',
      name:'Cinema',
			component:()=>import('@/views/Cinema'),
		},
		{
			path:'/develop',
			name:'Develop',
			component:()=>import('@/components/Develop')
		},
		//路由重定向到/movie
    {
		path:'/*',
		redirect:'/movie'
    }
  ]
})
